// ============================================================
// Amin AI World — data.js | Complete Edition
// ============================================================

const PROFILE = {
  name: "Mohammad AL Amin",
  channel: "চারপাশে যা দেখছি",
  bio: "AI প্রযুক্তি নিয়ে কাজ করি। বাংলা ভাষায় AI প্রম্পট ও টুলসের তথ্য সবার জন্য সহজলভ্য করার চেষ্টা করছি। Digital Creator | Entrepreneur | Content Strategist — Dhaka, Bangladesh",
  youtube: "https://youtube.com/@charpashezadekhchi?si=vNa2biVYhnysXzvs",
  facebook: "https://www.facebook.com/share/1Ft3jxtbvx/",
  facebookPage: "https://www.facebook.com/share/1DRgjnsLRv/",
  avatarImage: "images/amin-profile.png",
  avatarGradient: "linear-gradient(135deg,#E10600,#1a1a1a)"
};

const SOCIAL_LINKS = [
  {id:"s1",name:"YouTube",icon:"▶",color:"#FF0000",link:"https://youtube.com/@charpashezadekhchi?si=vNa2biVYhnysXzvs",desc:"চারপাশে যা দেখছি চ্যানেল"},
  {id:"s2",name:"Facebook Profile",icon:"f",color:"#1877F2",link:"https://www.facebook.com/share/1Ft3jxtbvx/",desc:"আমার ফেসবুক প্রোফাইল"},
  {id:"s3",name:"Facebook Page",icon:"f",color:"#1877F2",link:"https://www.facebook.com/share/1DRgjnsLRv/",desc:"চারপাশে যা দেখছি পেজ"},
  {id:"s4",name:"Instagram",icon:"📸",color:"#E1306C",link:"https://www.instagram.com/",desc:"Instagram প্রোফাইল"},
  {id:"s5",name:"TikTok",icon:"♪",color:"#010101",link:"https://www.tiktok.com/",desc:"TikTok চ্যানেল"},
  {id:"s6",name:"Threads",icon:"@",color:"#000000",link:"https://www.threads.net/",desc:"Threads প্রোফাইল"},
  {id:"s7",name:"Telegram",icon:"✈",color:"#0088cc",link:"https://t.me/",desc:"Telegram চ্যানেল"},
  {id:"s8",name:"WhatsApp",icon:"💬",color:"#25D366",link:"https://wa.me/",desc:"WhatsApp কমিউনিটি"},
  {id:"s9",name:"Vigo Live",icon:"🔴",color:"#E94560",link:"https://www.vigolive.com/",desc:"Vigo Live স্ট্রিমিং"}
];

const MOVIE_LINKS = [
  {id:"mv1",name:"Movie Link BD",link:"https://movielinkbd.one/",desc:"সর্বশেষ বাংলা ও হিন্দি মুভি",badge:"ফ্রি"},
  {id:"mv2",name:"The Movie Box",link:"https://themoviebox.xyz/",desc:"হলিউড ও বলিউড মুভির বিশাল সংগ্রহ",badge:"ফ্রি"},
  {id:"mv3",name:"Cine Voodc",link:"https://cinevoodc.com/",desc:"নতুন মুভি ও ওয়েব সিরিজ",badge:"ফ্রি"},
  {id:"mv4",name:"MLWBD",link:"https://fojik.site/mlwbd.com",desc:"মুভি ডাউনলোডের জনপ্রিয় সাইট",badge:"ফ্রি"},
  {id:"mv5",name:"MLS BD",link:"https://mlsbd.co/",desc:"বাংলা সাবটাইটেল সহ মুভি",badge:"ফ্রি"},
  {id:"mv6",name:"Hoichoi",link:"https://hoichoi.tv/bd",desc:"বাংলাদেশের প্রিমিয়াম OTT প্ল্যাটফর্ম",badge:"প্রিমিয়াম"}
];

const TV_LINKS = [
  {id:"tv1",name:"Jago BD",link:"https://www.jagobd.com/",desc:"বাংলাদেশের সব টিভি চ্যানেল লাইভ দেখুন",icon:"📺"},
  {id:"tv2",name:"Fame Lack",link:"https://famelack.com/",desc:"অনলাইন লাইভ টিভি স্ট্রিমিং",icon:"📡"}
];

const INCOME_APPS = [
  {id:"ia1",name:"Self Digital",playLink:"https://play.google.com/store/apps/details?id=www.self_digital",videoId:"C4RWO0DsoZg",desc:"ডিজিটাল ইনকামের সেরা অ্যাপ — ঘরে বসেই আয় করুন",badge:"ফ্রি"},
  {id:"ia2",name:"Life Good BD",playLink:"https://play.google.com/store/apps/details?id=com.lifegoodbd.lifegood",videoId:"VXsjEJfrLXw",desc:"অনলাইন ইনকামের বিশ্বস্ত প্ল্যাটফর্ম",badge:"ফ্রি"}
];

const ARTICLES = [
  {id:"a1",title:"AI প্রম্পট লেখার ৫টি কৌশল",excerpt:"ভালো ফলাফল পেতে প্রম্পটে কী কী থাকা জরুরি।",date:"৩০ জুন, ২০২৬"}
];

const MUSIC = [
  {id:"m1",title:"কালা মেঘের ভেলা",youtubeId:"_nePq7EOCYc",category:"folk"},
  {id:"m2",title:"মানুষ অন্তরে এক বাহিরে এক",youtubeId:"uajs8FgJWdI",category:"inspirational"},
  {id:"m3",title:"গার্মেন্টস কন্যা",youtubeId:"VqcJG-kr0U0",category:"social"},
  {id:"m4",title:"পোষা পরান পাখি",youtubeId:"C7F7OXJyekA",category:"folk"},
  {id:"m5",title:"বিদেশ নামের কারাগারে",youtubeId:"rnfUtyQgQZY",category:"emotional"},
  {id:"m6",title:"Labour Day",youtubeId:"q9k4KNEhlUc",category:"social"},
  {id:"m7",title:"কত কথা জমে থাকে",youtubeId:"SK-P6WWYDTI",category:"emotional"},
  {id:"m8",title:"মনের মানুষ",youtubeId:"xX3Szbkol7o",category:"romantic"},
  {id:"m9",title:"আমার মায়ায় পইড়ো",youtubeId:"kYEOVc_auKE",category:"romantic"},
  {id:"m10",title:"বাবা",youtubeId:"7vUyLJv78Ow",category:"emotional"}
];

const PROMPTS = [
  // ===== বাংলাদেশি পোর্ট্রেট =====
  {id:"p001",title:"বৃষ্টিতে কলাপাতার ছাতা",titleEn:"Rain & Banana Leaf Shield",prompt:"Photorealistic portrait of a young South Asian man standing in heavy rain, holding a large green banana leaf as umbrella, blue mirror aviator sunglasses, wet black shirt, golden sunset bokeh, cinematic, 85mm f/1.8, 8K",tool:"Midjourney",tags:["portrait","rain","bangla","cinematic"],image:"images/rain-leaf.png",gradient:"linear-gradient(135deg,#1a6b3a,#f0a500)"},
  {id:"p002",title:"শাড়িতে নদীর ধারে",titleEn:"Saree by the Riverside",prompt:"Elegant Bengali woman in white and blue embroidered cotton saree, standing by calm river at golden hour, holding glasses thoughtfully, soft bokeh city lights, gold bangles, contemplative mood, cinematic photography, 8K ultra realistic",tool:"DALL·E 3",tags:["saree","bangla","portrait","river"],image:"images/saree-riverside.png",gradient:"linear-gradient(135deg,#0EA5E9,#d4a017)"},
  {id:"p003",title:"গ্রামীণ সকালে কৃষক",titleEn:"Village Farmer at Dawn",prompt:"Cinematic portrait of elderly Bengali farmer in traditional lungi and gamcha, misty paddy fields at dawn, golden morning light, wrinkled hands holding a hoe, National Geographic style, ultra realistic, 8K",tool:"Midjourney",tags:["bangla","village","farmer","cinematic"],gradient:"linear-gradient(135deg,#78350F,#FCD34D)"},
  {id:"p004",title:"ঢাকার রাতের অলিগলি",titleEn:"Dhaka Night Alley Portrait",prompt:"Street portrait of a confident young man in narrow colorful Old Dhaka alley at night, neon light reflections, rickshaws and merchants blurred in background, documentary style, shallow depth of field, ultra realistic, 8K",tool:"Midjourney",tags:["dhaka","street","portrait","urban"],gradient:"linear-gradient(135deg,#1E3A5F,#F97316)"},
  {id:"p005",title:"বাংলাদেশি বিবাহের কনে",titleEn:"Bangladeshi Wedding Bride",prompt:"Stunning Bangladeshi bride in rich red and gold silk Banarasi saree, heavy gold jewelry, intricate mehndi, decorated bridal throne with marigold flowers, soft warm studio lighting, ultra detailed, 8K",tool:"Midjourney",tags:["bride","wedding","bangla","luxury"],gradient:"linear-gradient(135deg,#B22222,#FFD700)"},
  {id:"p006",title:"পদ্মা নদীর সূর্যাস্ত",titleEn:"Padma River Sunset",prompt:"Breathtaking aerial shot of Padma river at golden sunset, countless water channels and islands, golden light turning water to molten copper, epic wide cinematic, 8K",tool:"Midjourney",tags:["landscape","river","aerial","bangla"],gradient:"linear-gradient(135deg,#F97316,#1E3A8A)"},
  {id:"p007",title:"কক্সবাজার সূর্যোদয়",titleEn:"Cox's Bazar Sunrise",prompt:"Breathtaking sunrise at Cox's Bazar beach, pink and golden sky reflected in wet sand, silhouette of fishing boats, ultra wide angle, long exposure, peaceful, 8K",tool:"DALL·E 3",tags:["beach","landscape","sunrise","bangla"],gradient:"linear-gradient(135deg,#F9A8D4,#F97316)"},
  {id:"p008",title:"সাজেকের মেঘ সমুদ্র",titleEn:"Sajek Cloud Ocean",prompt:"Epic aerial view of Sajek Valley Bangladesh, waves of clouds rolling between green mountain ridges at sunrise, tiny cottages on hilltops, breathtaking panorama, golden hour, 8K ultra wide cinematic",tool:"Midjourney",tags:["landscape","mountain","clouds","bangla"],gradient:"linear-gradient(135deg,#0EA5E9,#166534)"},
  {id:"p009",title:"রিকশাচালকের প্রতিকৃতি",titleEn:"Rickshaw Puller Portrait",prompt:"Street photography portrait of Dhaka rickshaw puller resting on colorfully decorated rickshaw at dusk, warm light, tired but dignified expression, documentary photography style, moody cinematic lighting, 8K",tool:"Midjourney",tags:["bangla","street","documentary","dhaka"],gradient:"linear-gradient(135deg,#78350F,#F59E0B)"},
  {id:"p010",title:"মাওয়া ঘাটে সন্ধ্যা",titleEn:"Evening at Mawa Ghat",prompt:"Wide cinematic shot of Padma river bank at Mawa Ghat during golden hour, lone boatman silhouette on wooden boat, warm orange and pink sky reflecting on vast river, mist on water, epic landscape, 8K",tool:"Midjourney",tags:["bangla","river","landscape","cinematic"],gradient:"linear-gradient(135deg,#F97316,#7C3AED)"},

  // ===== ইন্ডিয়ান =====
  {id:"p011",title:"ইন্ডিয়ান ব্রাইডাল পোর্ট্রেট",titleEn:"Indian Bridal Portrait",prompt:"Stunning Indian bride in rich red Banarasi silk lehenga, heavy gold jewelry including maang tikka and nath, intricate mehndi, palace corridor with marble pillars and flower petals, Vogue India editorial, cinematic warm lighting, 8K",tool:"Midjourney",tags:["indian","bridal","portrait","luxury"],image:"images/saree-lake-1.png",gradient:"linear-gradient(135deg,#B22222,#FFD700)"},
  {id:"p012",title:"রাজস্থানি নর্তকী",titleEn:"Rajasthani Dancer",prompt:"Beautiful Rajasthani woman performing classical dance, vibrant orange and red ghagra choli with mirror work, spinning with arms extended, colorful bangles, desert fort at golden hour, motion blur on skirt, ultra realistic, 8K",tool:"Midjourney",tags:["indian","dance","rajasthani","colorful"],gradient:"linear-gradient(135deg,#F97316,#DC2626)"},
  {id:"p013",title:"হোলি উৎসবে রঙিন মেয়ে",titleEn:"Holi Festival Girl",prompt:"Beautiful Indian girl laughing with joy during Holi festival, face and clothes covered in vibrant pink, yellow, blue and red powder, backlit by golden sunlight creating magical halo, ultra realistic, 8K",tool:"Stable Diffusion",tags:["indian","holi","festival","colorful"],gradient:"linear-gradient(135deg,#EC4899,#F59E0B)"},
  {id:"p014",title:"বলিউড স্টাইল পোর্ট্রেট",titleEn:"Bollywood Style Portrait",prompt:"Glamorous Indian actress-style portrait, stunning royal blue silk saree with heavy embroidery, dramatic Bollywood makeup with bold red lips, elaborate gold jewelry, studio lighting, magazine cover quality, 8K",tool:"Midjourney",tags:["indian","bollywood","glamour","portrait"],gradient:"linear-gradient(135deg,#1E40AF,#DC2626)"},
  {id:"p015",title:"মুম্বাই স্ট্রিট ফ্যাশন",titleEn:"Mumbai Street Fashion",prompt:"Stylish young Indian man in designer streetwear, oversized hoodie, cargo pants, sneakers, leaning against graffiti wall in Mumbai, bokeh city lights, street photography, cinematic color grading, 8K",tool:"Midjourney",tags:["indian","street","fashion","urban"],gradient:"linear-gradient(135deg,#1E3A8A,#F97316)"},
  {id:"p016",title:"গোয়ার সমুদ্র সৈকতে",titleEn:"Goa Beach Portrait",prompt:"Free-spirited Indian girl in colorful bohemian dress walking barefoot on Goa beach at sunset, long wavy hair blowing in sea breeze, waves washing her feet, golden hour light, travel photography, 8K",tool:"Midjourney",tags:["indian","beach","goa","sunset"],gradient:"linear-gradient(135deg,#0EA5E9,#F97316)"},
  {id:"p017",title:"তাজ মহলের সামনে",titleEn:"In Front of Taj Mahal",prompt:"Beautiful Indian woman in white saree standing in front of Taj Mahal at golden hour, soft focus on monument behind her, gentle wind blowing fabric, warm romantic photography, ultra realistic, 8K",tool:"DALL·E 3",tags:["indian","taj","romantic","travel"],gradient:"linear-gradient(135deg,#DBEAFE,#F59E0B)"},

  // ===== পাকিস্তানি =====
  {id:"p018",title:"পাকিস্তানি স্টাইলিশ ম্যান",titleEn:"Pakistani Stylish Man",prompt:"Stylish Pakistani man in navy blue shalwar kameez with subtle embroidery, standing against Mughal architecture, confident expression, well-groomed beard, silver watch, editorial photography, dramatic lighting, 8K",tool:"Midjourney",tags:["pakistan","stylish","portrait","editorial"],gradient:"linear-gradient(135deg,#01411C,#FFFFFF)"},
  {id:"p019",title:"লাহোরি ওয়েডিং ব্রাইড",titleEn:"Lahori Wedding Bride",prompt:"Gorgeous Pakistani bride in emerald green and gold bridal lehenga with heavy embroidery, large gold jhoomar on forehead, kohl-lined eyes, intricate mehndi, decorated backdrop with roses, ultra realistic, 8K",tool:"Midjourney",tags:["pakistan","wedding","bride","luxury"],gradient:"linear-gradient(135deg,#065F46,#FFD700)"},
  {id:"p020",title:"করাচির আধুনিক মেয়ে",titleEn:"Modern Karachi Girl",prompt:"Modern Pakistani girl in stylish western outfit with colorful dupatta, walking confidently on busy Karachi street at night, neon signs and bokeh behind her, fashion street photography, ultra realistic, 8K",tool:"Stable Diffusion",tags:["pakistan","street","fashion","modern"],gradient:"linear-gradient(135deg,#7C3AED,#EC4899)"},

  // ===== রোমান্টিক / কাপল =====
  {id:"p021",title:"বাংলাদেশি কাপল সানসেট",titleEn:"Bangladeshi Couple Sunset",prompt:"Romantic Bengali couple at Buriganga river bank at golden sunset, woman in red Jamdani saree, man in white panjabi, holding hands, boats and river bokeh, warm cinematic lighting, ultra realistic, 8K",tool:"Midjourney",tags:["couple","romantic","bangla","sunset"],gradient:"linear-gradient(135deg,#FF6B35,#F7C59F)"},
  {id:"p022",title:"রোমান্টিক কাপল বৃষ্টিতে",titleEn:"Romantic Couple in Rain",prompt:"Romantic South Asian couple under one umbrella in heavy rain at night, neon lights reflecting in puddles, woman in red dress, man in dark suit, looking lovingly at each other, cinematic bokeh, ultra realistic, 8K",tool:"Stable Diffusion",tags:["couple","romantic","rain","cinematic"],gradient:"linear-gradient(135deg,#FF2D55,#1C1C3A)"},
  {id:"p023",title:"ছাদে চাঁদের আলোয়",titleEn:"Moonlight Rooftop Couple",prompt:"Dreamy couple on rooftop at night, full moon glowing above, city lights twinkling in distance, woman leaning on man's shoulder, fairy lights strung around them, soft romantic photography, ultra realistic, 8K",tool:"Midjourney",tags:["couple","romantic","night","moonlight"],gradient:"linear-gradient(135deg,#1E1B4B,#C4B5FD)"},
  {id:"p024",title:"কফি শপে প্রথম দেখা",titleEn:"First Meet at Coffee Shop",prompt:"Young South Asian couple having coffee at cozy cafe, first date energy, shy smiles, warm interior bokeh, coffee cups on wooden table between them, candid photography style, soft cinematic tones, ultra realistic, 8K",tool:"Stable Diffusion",tags:["couple","romantic","cafe","candid"],gradient:"linear-gradient(135deg,#92400E,#FDE68A)"},
  {id:"p025",title:"সমুদ্র সৈকতে প্রেম",titleEn:"Love at the Beach",prompt:"Beautiful couple walking hand in hand along pristine beach at sunset, waves washing their feet, woman in white flowy dress, man in linen shirt, golden hour silhouette, travel photography, ultra realistic, 8K",tool:"DALL·E 3",tags:["couple","beach","romantic","sunset"],gradient:"linear-gradient(135deg,#0EA5E9,#F97316)"},
  {id:"p026",title:"ইন্ডিয়ান কাপল হোলিতে",titleEn:"Indian Couple in Holi",prompt:"Joyful Indian couple throwing colorful Holi powder at each other, faces covered in pink, yellow and green colors, laughing and playing, garden setting, bright daylight, freeze frame action photography, 8K",tool:"Midjourney",tags:["couple","holi","indian","colorful"],gradient:"linear-gradient(135deg,#EC4899,#F59E0B)"},
  {id:"p027",title:"পাহাড়ে কাপল ট্রেকিং",titleEn:"Couple Trekking Mountains",prompt:"Adventurous couple holding hands on mountain trail at sunrise, woman in red jacket, man in blue jacket, dramatic Himalayan peaks behind, morning mist below, epic landscape photography, ultra realistic, 8K",tool:"DALL·E 3",tags:["couple","adventure","mountain","trekking"],gradient:"linear-gradient(135deg,#1E3A8A,#DC2626)"},
  {id:"p028",title:"ফুলের বাগানে প্রেম",titleEn:"Love in Flower Garden",prompt:"Romantic South Asian couple in a lavender flower field, man holding woman's hand and looking at her lovingly, golden hour backlight, dreamy bokeh, ultra romantic, cinematic photography, 8K",tool:"Midjourney",tags:["couple","romantic","flowers","dreamy"],gradient:"linear-gradient(135deg,#C4B5FD,#EC4899)"},
  {id:"p029",title:"বিবাহ বার্ষিকী",titleEn:"Wedding Anniversary Portrait",prompt:"Loving couple celebrating wedding anniversary in rooftop garden with fairy lights and roses, woman in elegant red dress, man in dark blazer, gazing into each other's eyes, soft warm bokeh, ultra romantic, 8K",tool:"Midjourney",tags:["couple","anniversary","romantic","luxury"],gradient:"linear-gradient(135deg,#DC2626,#F9A8D4)"},
  {id:"p030",title:"রেইনি ডে কিস",titleEn:"Rainy Day Kiss",prompt:"Cinematic close-up of a South Asian couple sharing a tender kiss in the rain, water droplets on faces, warm neon light from cafe window behind them, romantic blur, ultra realistic, 8K",tool:"Midjourney",tags:["couple","romantic","rain","kiss"],gradient:"linear-gradient(135deg,#1C1C3A,#FF6B9D)"},

  // ===== দুঃখ / আবেগময় =====
  {id:"p031",title:"একাকী বৃষ্টিতে",titleEn:"Lonely in the Rain",prompt:"Sad young South Asian woman standing alone in heavy rain at night, soaked in rain, looking down at her reflection in a puddle, city lights blurred around her, melancholic cinematic mood, 8K",tool:"Midjourney",tags:["sad","emotional","rain","portrait"],gradient:"linear-gradient(135deg,#1E3A8A,#374151)"},
  {id:"p032",title:"বিদায়ের মুহূর্ত",titleEn:"Moment of Goodbye",prompt:"Emotional farewell scene at airport, South Asian couple holding hands for the last time, tears in their eyes, blurred crowd around them, warm sad lighting, cinematic documentary style, ultra realistic, 8K",tool:"Stable Diffusion",tags:["sad","emotional","farewell","love"],gradient:"linear-gradient(135deg,#374151,#9CA3AF)"},
  {id:"p033",title:"একাকী সমুদ্র তটে",titleEn:"Alone by the Seashore",prompt:"Solitary South Asian man sitting on a rocky seashore at stormy sunset, waves crashing around him, head bowed in deep thought, dramatic moody lighting, contemplative sadness, ultra cinematic, 8K",tool:"Midjourney",tags:["sad","solitary","ocean","emotional"],gradient:"linear-gradient(135deg,#0C4A6E,#374151)"},
  {id:"p034",title:"পুরনো চিঠি",titleEn:"Old Love Letters",prompt:"Sad South Asian woman sitting by window on a rainy day, holding old love letters, tears on her cheeks, warm but melancholic interior lighting, dust and memories in the air, ultra realistic, 8K",tool:"DALL·E 3",tags:["sad","love","letters","emotional"],gradient:"linear-gradient(135deg,#78350F,#374151)"},
  {id:"p035",title:"শেষ বিদায়",titleEn:"Final Farewell",prompt:"Heartbreaking scene of a South Asian woman at a cemetery, kneeling by a gravestone, single white flower in hand, overcast sky with soft rain, emotional documentary photography, ultra realistic, 8K",tool:"Midjourney",tags:["sad","grief","emotional","portrait"],gradient:"linear-gradient(135deg,#1F2937,#6B7280)"},
  {id:"p036",title:"একা রাতের শহর",titleEn:"Alone in City at Night",prompt:"Lonely South Asian man standing on empty rain-soaked city bridge at midnight, neon lights reflected in water below, hands in pockets, head slightly down, melancholic urban solitude, cinematic, 8K",tool:"Midjourney",tags:["sad","city","night","solitary"],gradient:"linear-gradient(135deg,#1C1C3A,#4B5563)"},
  {id:"p037",title:"ভাঙা ভালোবাসা",titleEn:"Broken Love",prompt:"Emotional conceptual art: two hands slowly letting go of each other in soft light, one hand turning into fading smoke, symbolic of lost love, minimalist surreal composition, ultra cinematic, 8K",tool:"Stable Diffusion",tags:["sad","love","conceptual","emotional"],gradient:"linear-gradient(135deg,#374151,#DC2626)"},
  {id:"p038",title:"দূরে থাকা প্রিয়জন",titleEn:"Loved One Far Away",prompt:"South Asian woman at airport window watching plane disappear into cloudy sky, one hand on glass, tears running down cheek, soft warm light from window, ultra realistic emotional portrait, 8K",tool:"DALL·E 3",tags:["sad","love","farewell","emotional"],gradient:"linear-gradient(135deg,#1E3A8A,#6B7280)"},

  // ===== ভালোবাসা / Love =====
  {id:"p039",title:"প্রথম প্রেমের অনুভূতি",titleEn:"Feeling of First Love",prompt:"Beautiful South Asian teenage girl holding a single red rose, shy smile, sunlit school garden background, fresh and innocent mood, golden afternoon light, Bollywood romance aesthetic, ultra realistic, 8K",tool:"Midjourney",tags:["love","innocent","portrait","romantic"],gradient:"linear-gradient(135deg,#FF6B9D,#FFC371)"},
  {id:"p040",title:"লাভ লেটার",titleEn:"Love Letter",prompt:"Young South Asian man writing a love letter by candlelight, warm intimate setting, old wooden desk, dried rose petals around, vintage romantic mood, ultra detailed, 8K",tool:"Midjourney",tags:["love","romantic","vintage","mood"],gradient:"linear-gradient(135deg,#92400E,#FDE68A)"},
  {id:"p041",title:"তুমি আমার সব",titleEn:"You Are My Everything",prompt:"Intimate close-up of South Asian couple's hands intertwined, matching wedding rings visible, soft golden bokeh background, warm romantic lighting, symbolic love photography, ultra sharp, 8K",tool:"DALL·E 3",tags:["love","couple","wedding","intimate"],gradient:"linear-gradient(135deg,#B22222,#FFD700)"},
  {id:"p042",title:"প্রেমের গান",titleEn:"Love Song",prompt:"Beautiful South Asian woman in white dress singing with eyes closed in golden field at sunset, long flowing hair, white doves flying around her, dreamy romantic music video aesthetic, ultra realistic, 8K",tool:"Midjourney",tags:["love","music","dreamy","romantic"],gradient:"linear-gradient(135deg,#FDE68A,#F97316)"},
  {id:"p043",title:"রাত তিনটায় তোমার কথা",titleEn:"Thinking of You at 3AM",prompt:"South Asian girl lying on bed staring at her phone in dark room at 3am, only the phone screen illuminating her face, small smile on her lips, relatable late night love mood, ultra realistic, 8K",tool:"Stable Diffusion",tags:["love","night","relatable","mood"],gradient:"linear-gradient(135deg,#1C1C3A,#EC4899)"},
  {id:"p044",title:"ফুলের উপহার",titleEn:"Bouquet of Flowers",prompt:"Handsome South Asian young man surprising his girlfriend with a large bouquet of red roses, her surprised joyful expression, warm cozy home background, candid romantic moment, ultra realistic, 8K",tool:"Midjourney",tags:["love","couple","flowers","surprise"],gradient:"linear-gradient(135deg,#DC2626,#F9A8D4)"},

  // ===== ট্রেন্ডিং / Viral =====
  {id:"p045",title:"AI ব্রাইডাল মেকওভার",titleEn:"AI Bridal Makeover",prompt:"Stunning South Asian woman before and after AI bridal makeover, left side natural look, right side full bridal makeup with red lips, heavy eye makeup, gold jewelry, flawless skin, ultra realistic, trending viral format, 8K",tool:"Midjourney",tags:["trending","bridal","makeover","viral"],gradient:"linear-gradient(135deg,#7C3AED,#EC4899)"},
  {id:"p046",title:"ট্রেন্ডিং ব্লু আই মেকআপ",titleEn:"Trending Blue Eye Makeup",prompt:"Ultra close-up of South Asian woman's eyes with stunning trending blue eyeshadow, perfect winged liner, long curled lashes, editorial makeup photography, extreme detail of eye texture, ultra sharp, 8K",tool:"Midjourney",tags:["trending","makeup","eyes","fashion"],gradient:"linear-gradient(135deg,#1E40AF,#EC4899)"},
  {id:"p047",title:"ভাইরাল সূর্যাস্ত পোর্ট্রেট",titleEn:"Viral Sunset Portrait",prompt:"Viral-worthy golden hour portrait of beautiful South Asian woman, sun behind her creating perfect lens flare halo, skin glowing, minimal outfit, ultra warm tones, Instagram-perfect composition, 8K",tool:"Midjourney",tags:["trending","sunset","viral","portrait"],gradient:"linear-gradient(135deg,#F97316,#FCD34D)"},
  {id:"p048",title:"ট্রেন্ডিং অ্যানিমে স্টাইল",titleEn:"Trending Anime Style",prompt:"Stunning South Asian woman reimagined as anime character, large expressive eyes, detailed anime hair with soft highlights, colorful outfit, cherry blossom background, high quality anime art style, trending on social media, 8K",tool:"Stable Diffusion",tags:["trending","anime","art","creative"],gradient:"linear-gradient(135deg,#FF6B9D,#7C3AED)"},
  {id:"p049",title:"ট্রেন্ডিং প্রোডাক্টিভিটি অ্যাস্থেটিক",titleEn:"Trending Productivity Aesthetic",prompt:"Trendy flat lay of productive morning aesthetic: laptop, coffee, journal, headphones, plants, on marble surface, soft natural light, warm brown and cream tones, trending study aesthetic, ultra detailed, 8K",tool:"DALL·E 3",tags:["trending","aesthetic","lifestyle","study"],gradient:"linear-gradient(135deg,#92400E,#D1FAE5)"},
  {id:"p050",title:"ট্রেন্ডিং সিলুয়েট ড্যান্স",titleEn:"Trending Silhouette Dance",prompt:"Viral silhouette challenge: beautiful South Asian woman's silhouette dancing against glowing neon red-orange window, perfect graceful pose, trending social media format, ultra cinematic, 8K",tool:"Midjourney",tags:["trending","silhouette","dance","viral"],gradient:"linear-gradient(135deg,#DC2626,#000000)"},

  // ===== সিনেমাটিক =====
  {id:"p051",title:"সিনেমাটিক ভিলেজ গার্ল",titleEn:"Cinematic Village Girl",prompt:"Cinematic portrait of beautiful Bengali village girl in yellow cotton saree, sitting beside clay pot under banyan tree, morning mist in rice fields, natural sunlight through leaves, National Geographic style, ultra realistic, 8K",tool:"Midjourney",tags:["bangla","village","cinematic","portrait"],gradient:"linear-gradient(135deg,#F59E0B,#10B981)"},
  {id:"p052",title:"নিওন সিটি রাতে",titleEn:"Neon City at Night",prompt:"Ultra cinematic shot of rain-soaked Asian city street at night, neon signs reflecting in puddles, lone figure in trench coat, steam rising from manholes, cyberpunk atmosphere, 35mm anamorphic, 8K",tool:"Midjourney",tags:["city","night","cinematic","cyberpunk"],gradient:"linear-gradient(135deg,#7C3AED,#EC4899)"},
  {id:"p053",title:"যোদ্ধার বিজয়",titleEn:"Warrior's Victory",prompt:"Epic cinematic shot of South Asian warrior woman in ornate golden armor on cliff, sword raised toward stormy sky, lightning in background, dramatic wind blowing cape, movie poster quality, ultra realistic, 8K",tool:"Midjourney",tags:["warrior","epic","cinematic","fantasy"],gradient:"linear-gradient(135deg,#78350F,#F59E0B)"},
  {id:"p054",title:"গোয়েন্দার গল্প",titleEn:"Detective Story",prompt:"Noir cinematic portrait of South Asian detective in 1940s style, trench coat and fedora hat, standing under street lamp in foggy night, shadows across face, holding case file, ultra cinematic, 8K",tool:"Stable Diffusion",tags:["cinematic","detective","noir","dramatic"],gradient:"linear-gradient(135deg,#1F2937,#6B7280)"},
  {id:"p055",title:"মোগল রাজপুত্র",titleEn:"Mughal Prince",prompt:"Majestic Mughal prince in elaborate embroidered sherwani with turban adorned with peacock feather and gems, jeweled throne, intricate palace interior with marble inlay, dramatic cinematic lighting, 8K",tool:"Midjourney",tags:["mughal","historical","portrait","royal"],gradient:"linear-gradient(135deg,#92400E,#7C3AED)"},
  {id:"p056",title:"সমুদ্রের গভীরে নর্তকী",titleEn:"Underwater Dancer",prompt:"Surreal cinematic underwater portrait of graceful South Asian woman in flowing red silk dress dancing beneath ocean, hair and fabric flowing upward, tropical fish around her, rays of light from above, 8K",tool:"Midjourney",tags:["underwater","surreal","cinematic","dance"],gradient:"linear-gradient(135deg,#0C4A6E,#DC2626)"},
  {id:"p057",title:"মরুভূমির রাণী",titleEn:"Desert Queen",prompt:"Majestic South Asian queen in elaborate golden desert robes, sitting on ornate throne atop sand dunes at sunset, jewel-encrusted crown, fierce expression, camels silhouetted in background, epic cinematic widescreen, 8K",tool:"Midjourney",tags:["queen","desert","epic","cinematic"],gradient:"linear-gradient(135deg,#92400E,#FCD34D)"},

  // ===== অ্যাডভেঞ্চার =====
  {id:"p058",title:"অ্যাডভেঞ্চার হাইকার গার্ল",titleEn:"Adventure Hiker Girl",prompt:"Bold adventurous South Asian woman on rocky mountain peak at sunrise, red hiking gear and backpack, arms spread wide, dramatic clouds below, golden hour light, epic landscape, ultra wide angle, cinematic, 8K",tool:"Midjourney",tags:["adventure","girl","mountain","epic"],gradient:"linear-gradient(135deg,#FF4500,#1a1a2e)"},
  {id:"p059",title:"স্কাইডাইভিং পিওভি",titleEn:"Skydiving POV",prompt:"First-person POV of skydiver free-falling above scattered clouds, sunlight breaking through, patchwork landscape far below, extreme sports photography, GoPro style, high adrenaline, ultra realistic, 8K",tool:"Midjourney",tags:["skydiving","adventure","sky","extreme"],gradient:"linear-gradient(135deg,#1E3A8A,#60A5FA)"},
  {id:"p060",title:"মোটরসাইকেল হাইওয়ে",titleEn:"Motorcycle Highway",prompt:"Cinematic shot of South Asian man on powerful motorcycle speeding down empty coastal highway at sunset, sea on one side, mountains on other, wind blur effect, adventure travel photography, ultra realistic, 8K",tool:"Midjourney",tags:["motorcycle","adventure","highway","sunset"],gradient:"linear-gradient(135deg,#1F2937,#F97316)"},
  {id:"p061",title:"জঙ্গলে এক্সপ্লোরার",titleEn:"Jungle Explorer",prompt:"Adventurous young woman as jungle explorer pushing through dense tropical rainforest, wearing khaki explorer outfit, machete in hand, sunlight breaking through forest canopy creating god rays, butterflies, ultra realistic, 8K",tool:"Midjourney",tags:["adventure","jungle","explorer","nature"],gradient:"linear-gradient(135deg,#166534,#F59E0B)"},
  {id:"p062",title:"সার্ফিং বিশাল ঢেউয়ে",titleEn:"Surfing Giant Waves",prompt:"Epic action shot of South Asian surfer riding massive 30-foot ocean wave, water spray exploding around surfboard, dramatic lighting, ultra wide angle, extreme sports photography, freeze frame, ultra realistic, 8K",tool:"Stable Diffusion",tags:["surfing","adventure","ocean","extreme"],gradient:"linear-gradient(135deg,#0C4A6E,#7DD3FC)"},

  // ===== স্টাইলিশ মহিলা =====
  {id:"p063",title:"ফ্যাশন ম্যাগাজিন কভার",titleEn:"Fashion Magazine Cover",prompt:"High fashion magazine cover of stunning South Asian model in avant-garde designer outfit, bold geometric patterns, professional studio lighting, Vogue quality, dramatic pose, ultra sharp, 8K",tool:"Midjourney",tags:["fashion","model","magazine","editorial"],gradient:"linear-gradient(135deg,#1F2937,#EC4899)"},
  {id:"p064",title:"সানসেট মডেল শুট",titleEn:"Sunset Model Shoot",prompt:"Professional fashion shoot of beautiful South Asian model in flowing silk dress on rooftop at magic hour, wind dramatically blowing fabric, Mumbai skyline in background, golden hour lighting, Vogue India quality, ultra realistic, 8K",tool:"Midjourney",tags:["fashion","model","sunset","editorial"],gradient:"linear-gradient(135deg,#FF6B35,#7C3AED)"},
  {id:"p065",title:"সূর্যাস্তে নীল পোশাক",titleEn:"Blue Dress in Sunset Water",prompt:"Beautiful South Asian woman in navy blue floral dress standing in shallow water during vivid pink sunset, holding white heels, splashing water, long dark wavy hair, dramatic sky reflection on water, cinematic, 8K",tool:"Midjourney",tags:["portrait","sunset","water","romantic"],image:"images/sunset-water.png",gradient:"linear-gradient(135deg,#FF6B9D,#FF9A5C)"},
  {id:"p066",title:"বোহেমিয়ান ট্রাভেলার",titleEn:"Bohemian Traveler Girl",prompt:"Free-spirited South Asian woman in colorful bohemian maxi dress and floral crown, sitting on vintage VW van on empty desert road, sunset behind her, travel adventure aesthetic, ultra realistic, 8K",tool:"Stable Diffusion",tags:["girl","travel","bohemian","adventure"],gradient:"linear-gradient(135deg,#F97316,#7C3AED)"},
  {id:"p067",title:"কর্পোরেট পাওয়ার উইমেন",titleEn:"Corporate Power Woman",prompt:"Powerful South Asian businesswoman in sharp navy power suit, floor-to-ceiling glass windows overlooking city skyline at golden hour, confident authoritative pose, Forbes magazine quality, ultra realistic, 8K",tool:"Midjourney",tags:["woman","business","corporate","powerful"],gradient:"linear-gradient(135deg,#1E3A8A,#F59E0B)"},
  {id:"p068",title:"শাড়িতে কফি টাইম",titleEn:"Coffee Time in Saree",prompt:"Elegant South Asian woman in pastel pink Organza saree at cafe window seat with cappuccino, morning light filtering in, city outside blurred, peaceful thoughtful expression, lifestyle photography, ultra realistic, 8K",tool:"DALL·E 3",tags:["saree","lifestyle","coffee","elegant"],gradient:"linear-gradient(135deg,#FDF2F8,#EC4899)"},
  {id:"p069",title:"গিটার গার্ল সানসেট",titleEn:"Guitar Girl at Sunset",prompt:"Beautiful South Asian girl sitting on cliff edge playing acoustic guitar at sunset, ocean below, golden light bathing her face, long hair blowing in breeze, cinematic peaceful atmosphere, ultra realistic, 8K",tool:"Midjourney",tags:["girl","guitar","sunset","music"],gradient:"linear-gradient(135deg,#F59E0B,#DC2626)"},

  // ===== স্টাইলিশ পুরুষ =====
  {id:"p070",title:"গিটার বাদকের পোর্ট্রেট",titleEn:"Dark Studio Guitar Portrait",prompt:"Cinematic close-up of young South Asian musician playing acoustic guitar in dramatic dark studio, deep teal kurta, silver aviator sunglasses, warm golden rim light on strings, moody editorial, 85mm f/1.2, 8K",tool:"Midjourney",tags:["guitar","music","portrait","dark"],image:"images/guitar-dark.png",gradient:"linear-gradient(135deg,#0D4F4F,#C8B400)"},
  {id:"p071",title:"স্টাইলিশ দাড়ি ওয়ালা",titleEn:"Stylish Bearded Man",prompt:"Portrait of confident South Asian man with dramatic full curly beard with auburn highlights, deep purple linen shirt, sitting relaxed on grey couch with iPhone, luxury silver watch, warm Edison bulb lighting, neon pink bokeh, editorial, 8K",tool:"Leonardo AI",tags:["portrait","stylish","beard","editorial"],image:"images/purple-man.jpg",gradient:"linear-gradient(135deg,#6B21A8,#EC4899)"},
  {id:"p072",title:"আর্জেন্টিনা জার্সি",titleEn:"Argentina Jersey Portrait",prompt:"Confident young South Asian man in Argentina football #10 jersey against bold pink-red gradient wall, blue mirror aviators, casual confident pose, street photography, ultra sharp, 8K",tool:"Midjourney",tags:["portrait","football","sport","street"],image:"images/argentina-jersey.png",gradient:"linear-gradient(135deg,#75AADB,#FFFFFF)"},
  {id:"p073",title:"টেক উদ্যোক্তা",titleEn:"Tech Entrepreneur Portrait",prompt:"Young South Asian tech entrepreneur in smart casual outfit, modern glass office with multiple screens showing code and dashboards, confident innovative look, silicon valley style photography, ultra realistic, 8K",tool:"DALL·E 3",tags:["tech","entrepreneur","business","modern"],gradient:"linear-gradient(135deg,#0EA5E9,#7C3AED)"},
  {id:"p074",title:"প্রফেশনাল হেডশট",titleEn:"Professional Headshot",prompt:"Clean professional headshot of young South Asian man in cobalt blue formal shirt against pure white background, natural warm smile, neat black hair, studio lighting with soft shadows, corporate photography, ultra sharp, 8K",tool:"DALL·E 3",tags:["headshot","professional","corporate","portrait"],image:"images/blue-shirt.png",gradient:"linear-gradient(135deg,#1E40AF,#FFFFFF)"},

  // ===== ফ্যান্টাসি / আর্ট =====
  {id:"p075",title:"ড্রাগন রাইডার",titleEn:"Dragon Rider",prompt:"Epic armored warrior riding massive ice dragon above snowy mountain peaks, epic fantasy art, dramatic clouds, dynamic pose, trending on ArtStation, hyper detailed scales, 8K",tool:"Midjourney",tags:["fantasy","dragon","epic","warrior"],gradient:"linear-gradient(135deg,#4DE8FF,#2541B2)"},
  {id:"p076",title:"এলফ রাজকুমারী",titleEn:"Elven Princess",prompt:"Stunning South Asian elven princess with pointed ears and long dark hair, intricate silver armor with gold filigree, mystical forest with glowing fireflies, magical fantasy art, ultra detailed, 8K",tool:"Stable Diffusion",tags:["fantasy","elf","princess","magic"],gradient:"linear-gradient(135deg,#166534,#7C3AED)"},
  {id:"p077",title:"সাইবারপাঙ্ক শহর",titleEn:"Cyberpunk City",prompt:"Rain-soaked cyberpunk megacity street at night, neon signs reflecting in puddles, flying cars in distance, cinematic lighting, ultra detailed, 35mm lens, volumetric fog, 8K",tool:"Midjourney",tags:["cyberpunk","city","night","scifi"],gradient:"linear-gradient(135deg,#FF2E63,#1B1B3A)"},
  {id:"p078",title:"AI রোবট পোর্ট্রেট",titleEn:"AI Robot Portrait",prompt:"Close-up portrait of humanoid robot with translucent skin showing glowing circuitry, soft rim lighting, photorealistic, shallow depth of field, Unreal Engine 5 render, 8K",tool:"Stable Diffusion",tags:["robot","scifi","portrait","ai"],gradient:"linear-gradient(135deg,#7C5CFF,#FF6B6B)"},
  {id:"p079",title:"ভবিষ্যতের ঢাকা",titleEn:"Future Dhaka 2100",prompt:"Futuristic vision of Dhaka city in 2100, flying cars over gleaming glass skyscrapers, elevated green bridges, clean river with electric boats, Bangladesh flag flying proudly, cinematic sci-fi cityscape, 8K",tool:"DALL·E 3",tags:["scifi","future","dhaka","concept"],gradient:"linear-gradient(135deg,#166534,#0EA5E9)"},
  {id:"p080",title:"জাদুকরী বন",titleEn:"Magical Forest",prompt:"Enchanted magical forest at night, glowing mushrooms and fireflies, ancient twisted trees with bioluminescent vines, South Asian girl in white dress looking up in wonder, ultra realistic fantasy art, 8K",tool:"Midjourney",tags:["fantasy","forest","magic","nature"],gradient:"linear-gradient(135deg,#065F46,#7C3AED)"},

  // ===== প্রকৃতি =====
  {id:"p081",title:"সুন্দরবনের বাঘ",titleEn:"Sundarbans Tiger",prompt:"Majestic Royal Bengal Tiger emerging from dense Sundarbans mangrove forest, partly submerged in amber water, intense golden eyes staring at camera, dramatic rim lighting, National Geographic quality, 8K",tool:"Midjourney",tags:["wildlife","tiger","nature","bangla"],gradient:"linear-gradient(135deg,#92400E,#166534)"},
  {id:"p082",title:"ময়ূরের পালক ক্লোজআপ",titleEn:"Peacock Feather Macro",prompt:"Extreme close-up macro of peacock tail feathers fanned out, vibrant iridescent blue and green eye patterns, soft natural light, ultra sharp micro detail, 8K macro photography",tool:"Midjourney",tags:["bird","nature","macro","colorful"],gradient:"linear-gradient(135deg,#0D9488,#7C5CFF)"},
  {id:"p083",title:"আইসল্যান্ডের অরোরা",titleEn:"Iceland Northern Lights",prompt:"Breathtaking Northern Lights dance over frozen Icelandic lake, vivid green and purple light curtains reflected perfectly in ice, snow-covered landscape, astrophotography, ultra realistic, 8K",tool:"Midjourney",tags:["worldwide","aurora","landscape","night"],gradient:"linear-gradient(135deg,#1E3A8A,#10B981)"},
  {id:"p084",title:"সাহারা মরুভূমির রাত",titleEn:"Sahara Desert Night",prompt:"Vast Sahara desert sand dunes under starry sky with Milky Way visible, lone camel silhouette, astrophotography style, long exposure, deep blue and orange tones, ultra realistic, 8K",tool:"Midjourney",tags:["worldwide","desert","night","stars"],gradient:"linear-gradient(135deg,#1B1B3A,#FF7E5F)"},
  {id:"p085",title:"জাপানের সাকুরা",titleEn:"Japan Cherry Blossom",prompt:"Traditional Japanese street lined with blooming cherry blossom trees, soft pink petals falling, ancient pagoda visible in background, serene spring atmosphere, golden hour, ultra realistic, 8K travel photography",tool:"Stable Diffusion",tags:["worldwide","japan","spring","travel"],gradient:"linear-gradient(135deg,#FFB6C1,#FF6B9D)"},

  // ===== ফানি / ক্রিয়েটিভ =====
  {id:"p086",title:"মহাকাশে বিরিয়ানি",titleEn:"Biryani in Space",prompt:"Hilarious hyper realistic: South Asian astronaut floating in space station, carefully eating biryani from clay pot in zero gravity, rice grains floating around, Earth visible through window, ultra realistic, 8K",tool:"Midjourney",tags:["funny","space","food","creative"],gradient:"linear-gradient(135deg,#1E1B4B,#F97316)"},
  {id:"p087",title:"বিড়ালের বস",titleEn:"Cat Boss",prompt:"Funny hyper realistic image of a cat wearing tiny business suit at executive office desk, glasses on nose, signing important documents, other cats as employees in background, Pixar-style, hilarious, 8K",tool:"Midjourney",tags:["funny","cat","creative","humor"],gradient:"linear-gradient(135deg,#7C3AED,#F59E0B)"},
  {id:"p088",title:"রিকশায় রাজকীয় যাত্রা",titleEn:"Royal Rickshaw Ride",prompt:"Hilarious: South Asian king in full royal robes and crown, riding a Dhaka cycle rickshaw through busy market street, looking completely serious and dignified, people staring in shock, cinematic comedy, ultra realistic, 8K",tool:"DALL·E 3",tags:["funny","creative","bangla","royal"],gradient:"linear-gradient(135deg,#92400E,#FCD34D)"},
  {id:"p089",title:"ফানি অফিস মিটিং",titleEn:"Funny Office Meeting",prompt:"Funny digital art: bored South Asian man in business suit secretly watching cricket on phone under table during serious board meeting, everyone staring at boring charts, subtle smirk, comic style, vibrant colors, 8K",tool:"DALL·E 3",tags:["funny","office","creative","comic"],image:"images/facebook-creative.jpg",gradient:"linear-gradient(135deg,#F59E0B,#3B82F6)"},
  {id:"p090",title:"সমুদ্রে ভেলায় ফুটবল",titleEn:"Football on Ocean Raft",prompt:"Surreal: South Asian man on plastic bottle raft in middle of ocean, sitting on sofa watching football on Samsung TV powered by Honda generator, blue shirt, aviator sunglasses, golden sunset, seagulls, 8K",tool:"Midjourney",tags:["surreal","funny","creative","ocean"],image:"images/football-ocean.png",gradient:"linear-gradient(135deg,#FF7E5F,#FEB47B)"},

  // ===== আপনার ছবি =====
  {id:"p091",title:"AI শাড়ি পোর্ট্রেট ১",titleEn:"AI Saree Portrait v1",prompt:"AI generated photorealistic Bengali woman in white and sky blue cotton saree with intricate border, leaning on railing by peaceful lake, holding glasses elegantly, soft evening bokeh, gold jewelry, cinematic warm tones, 85mm f/1.4, 8K",tool:"Stable Diffusion",tags:["ai-generated","saree","bangla","portrait"],image:"images/saree-lake-1.png",gradient:"linear-gradient(135deg,#87CEEB,#d4a017)"},
  {id:"p092",title:"AI শাড়ি পোর্ট্রেট ২",titleEn:"AI Saree Portrait v2",prompt:"AI generated hyperrealistic Bengali woman in traditional white and cyan cotton saree with geometric border, posed elegantly on riverside walkway at dusk, wind gently moving her hair, rich skin tone, professional fashion photography, 8K",tool:"Stable Diffusion",tags:["ai-generated","saree","elegant","dusk"],image:"images/saree-lake-2.png",gradient:"linear-gradient(135deg,#4DE8FF,#1B998B)"},
  {id:"p093",title:"গিটার বাদিকা ও পায়রা ১",titleEn:"Guitarist Girl with Doves 1",prompt:"Dreamy portrait of beautiful South Asian girl in flowing dusty rose tulle dress playing acoustic guitar in ancient ivy-covered stone garden at golden hour, white doves perched nearby, long dark wavy hair, magical fairytale atmosphere, 8K",tool:"Midjourney",tags:["portrait","guitar","romantic","fairytale"],image:"images/girl-guitar-doves-1.png",gradient:"linear-gradient(135deg,#D4A5A5,#F9E4B7)"},
  {id:"p094",title:"গিটার বাদিকা ও পায়রা ২",titleEn:"Guitarist Girl with Doves 2",prompt:"Photorealistic South Asian girl with auburn wavy long hair and red lips, wearing sheer rose-gold organza dress, playing wooden acoustic guitar on ancient mossy stone balcony, two white doves beside her, warm golden hour sunlight, romantic cinematic, 8K",tool:"Stable Diffusion",tags:["portrait","guitar","doves","cinematic"],image:"images/girl-guitar-doves-2.png",gradient:"linear-gradient(135deg,#C8976E,#F5DEB3)"},
  {id:"p095",title:"ফেসবুক ক্রিয়েটিভ পোর্ট্রেট",titleEn:"Facebook Creative Portrait",prompt:"Creative 3D composite: confident South Asian entrepreneur on bean bag with iPhone, surrounded by books on Focus, Discipline, Consistency, camera, laptop, plants and LED motivational signs, giant Facebook profile mockup with 256K followers, cherry blossoms, cinematic warm lighting",tool:"Midjourney",tags:["creative","social-media","composite","entrepreneur"],image:"images/facebook-creative.jpg",gradient:"linear-gradient(135deg,#1877F2,#f5a623)"},
  {id:"p096",title:"Amin AI World ব্র্যান্ড পোর্ট্রেট",titleEn:"Amin AI World Brand Portrait",prompt:"Ultra-realistic cinematic black-and-white portrait, confident young South Asian man, dramatic low-angle, bold visionary expression, silver aviator sunglasses, black knitted sweater, vibrant red rectangular background on white canvas, luxury branding, HDR, 8K, Hasselblad 85mm f/1.8",tool:"AI Portrait Generator",tags:["portrait","branding","editorial","amin"],image:"images/amin-profile.png",gradient:"linear-gradient(135deg,#E10600,#1a1a1a)"},
  {id:"p097",title:"বৃষ্টিতে কলাপাতার পোর্ট্রেট",titleEn:"Rain Portrait with Leaf",prompt:"Photorealistic portrait of a young South Asian man standing in heavy rain holding a large green banana leaf as umbrella, blue mirror aviator sunglasses, wet black shirt, lush green bokeh, golden sunset light filtering through rain, cinematic, 8K",tool:"Midjourney",tags:["portrait","rain","bangla","cinematic"],image:"images/rain-leaf.png",gradient:"linear-gradient(135deg,#1a6b3a,#f0a500)"},
  {id:"p098",title:"সমুদ্রে ভেলায় বসে",titleEn:"Ocean Raft Lifestyle",prompt:"Surreal cinematic image of young man on makeshift plastic bottle raft in open ocean, watching football on TV powered by generator, casual relaxed pose, seagulls in sky, incredible golden sunset over horizon, ultra realistic, 8K",tool:"Midjourney",tags:["creative","ocean","lifestyle","surreal"],image:"images/football-ocean.png",gradient:"linear-gradient(135deg,#0EA5E9,#F97316)"}
];

const TOOLS = [
  {id:"t1",name:"ChatGPT",category:"টেক্সট / চ্যাট",desc:"OpenAI-এর তৈরি শক্তিশালী AI — লেখা, কোড, বিশ্লেষণ, অনুবাদ সব কিছুতেই সহায়ক।",link:"https://chat.openai.com",free:true},
  {id:"t2",name:"Gemini",category:"টেক্সট / চ্যাট",desc:"Google-এর AI অ্যাসিস্ট্যান্ট — রিয়েল-টাইম Google সার্চ ও Workspace সংযুক্ত।",link:"https://gemini.google.com",free:true},
  {id:"t3",name:"Grok",category:"টেক্সট / চ্যাট",desc:"xAI (Elon Musk)-এর AI — রিয়েল-টাইম X/Twitter ডেটা সহ সরাসরি ও সৎ উত্তর দেয়।",link:"https://grok.com",free:true},
  {id:"t4",name:"Claude AI",category:"টেক্সট / চ্যাট",desc:"Anthropic-এর AI — লেখা, কোডিং ও বিশ্লেষণে অত্যন্ত নির্ভরযোগ্য ও নিরাপদ।",link:"https://claude.ai",free:true},
  {id:"t5",name:"Perplexity AI",category:"সার্চ / রিসার্চ",desc:"তথ্যসূত্রসহ উত্তর দেয় এমন AI সার্চ ইঞ্জিন — রিসার্চ ও ফ্যাক্ট চেকের জন্য সেরা।",link:"https://www.perplexity.ai",free:true},
  {id:"t6",name:"Midjourney",category:"ছবি জেনারেশন",desc:"টেক্সট প্রম্পট থেকে উচ্চমানের শৈল্পিক ছবি তৈরির সবচেয়ে জনপ্রিয় টুল।",link:"https://www.midjourney.com",free:false},
  {id:"t7",name:"DALL·E 3",category:"ছবি জেনারেশন",desc:"OpenAI-এর ছবি জেনারেটর — বিস্তারিত প্রম্পট বোঝায় অত্যন্ত দক্ষ।",link:"https://openai.com/dall-e-3",free:false},
  {id:"t8",name:"Stable Diffusion",category:"ছবি জেনারেশন",desc:"ওপেন-সোর্স ছবি জেনারেশন — ফ্রিতে অনলাইনে ও অফলাইনে চালানো যায়।",link:"https://stability.ai",free:true},
  {id:"t9",name:"Leonardo AI",category:"ছবি জেনারেশন",desc:"গেম আর্ট ও কনসেপ্ট ডিজাইনের জনপ্রিয় AI — প্রতিদিন ফ্রি ক্রেডিট দেয়।",link:"https://leonardo.ai",free:true},
  {id:"t10",name:"Ideogram",category:"ছবি জেনারেশন",desc:"AI ইমেজ জেনারেটর যা ছবির ভেতরে সঠিক টেক্সট বসাতে পারে — পোস্টার ও লোগোর জন্য আদর্শ।",link:"https://ideogram.ai",free:true},
  {id:"t11",name:"Adobe Firefly",category:"ছবি জেনারেশন",desc:"Adobe-এর AI ইমেজ টুল — Photoshop ও Illustrator-এর সাথে ইন্টিগ্রেটেড।",link:"https://firefly.adobe.com",free:true},
  {id:"t12",name:"Kling AI",category:"ভিডিও (অ্যাডভান্সড)",desc:"Kuaishou-এর অত্যাধুনিক AI ভিডিও জেনারেটর — ছবি বা টেক্সট থেকে হাই-কোয়ালিটি ভিডিও তৈরি।",link:"https://klingai.com",free:true},
  {id:"t13",name:"Seedance 2.0",category:"ভিডিও (অ্যাডভান্সড)",desc:"ByteDance-এর নতুন AI ভিডিও মডেল — সিনেমা-মানের ভিডিও তৈরিতে সক্ষম।",link:"https://seedance.ai",free:true},
  {id:"t14",name:"Runway ML",category:"ভিডিও",desc:"AI দিয়ে ভিডিও জেনারেশন ও এডিটিং, টেক্সট-টু-ভিডিও সমৃদ্ধ।",link:"https://runwayml.com",free:false},
  {id:"t15",name:"Luma Dream Machine",category:"ভিডিও (অ্যাডভান্সড)",desc:"ছবি বা টেক্সট থেকে অসাধারণ রিয়েলিস্টিক AI ভিডিও তৈরির টুল।",link:"https://lumalabs.ai/dream-machine",free:true},
  {id:"t16",name:"Pika",category:"ভিডিও",desc:"টেক্সট বা ছবি থেকে শর্ট AI ভিডিও তৈরির জনপ্রিয় ও সহজ টুল।",link:"https://pika.art",free:true},
  {id:"t17",name:"HeyGen",category:"ভিডিও / অ্যাভাটার",desc:"AI অ্যাভাটার দিয়ে কথা বলা ভিডিও তৈরি, ডিজিটাল ক্লোন ও ভয়েস ক্লোনিং।",link:"https://www.heygen.com",free:true},
  {id:"t18",name:"ElevenLabs",category:"ভয়েস / অডিও",desc:"টেক্সট-টু-স্পিচ ও ভয়েস ক্লোনিং — প্রাকৃতিক শোনায় এমন কণ্ঠ তৈরি করে।",link:"https://elevenlabs.io",free:true},
  {id:"t19",name:"Suno AI",category:"মিউজিক জেনারেশন",desc:"টেক্সট প্রম্পট থেকে সম্পূর্ণ গান তৈরি — কথা, সুর, ভোকাল সব একসাথে।",link:"https://suno.com",free:true},
  {id:"t20",name:"Canva AI",category:"ডিজাইন",desc:"AI দিয়ে পোস্টার, প্রেজেন্টেশন ও সোশ্যাল মিডিয়া ডিজাইন সহজে তৈরি।",link:"https://www.canva.com",free:true},
  {id:"t21",name:"Notion AI",category:"প্রোডাক্টিভিটি",desc:"Notion-এর মধ্যেই লেখা, সারাংশ ও আইডিয়া তৈরির AI সহায়তা।",link:"https://www.notion.so/product/ai",free:false},
  {id:"t22",name:"GitHub Copilot",category:"কোডিং",desc:"AI কোড সহকারী — প্রোগ্রামিং করার সময় কোড সাজেশন ও অটোকমপ্লিট দেয়।",link:"https://github.com/features/copilot",free:false},
  {id:"t23",name:"Deepseek",category:"টেক্সট / চ্যাট",desc:"চীনের শক্তিশালী ওপেন-সোর্স AI — কোডিং ও গণিতে বিশেষভাবে দক্ষ।",link:"https://www.deepseek.com",free:true},
  {id:"t24",name:"Meta AI",category:"টেক্সট / চ্যাট",desc:"Meta-এর AI — WhatsApp, Instagram, Facebook-এ সরাসরি ব্যবহার করা যায়।",link:"https://www.meta.ai",free:true},
  {id:"t25",name:"Copilot (Microsoft)",category:"টেক্সট / চ্যাট",desc:"Microsoft-এর AI — Windows, Office 365 ও Bing-এর সাথে ইন্টিগ্রেটেড।",link:"https://copilot.microsoft.com",free:true}
];
